### ISSUE TITLE
PEP 8 lesson organization and cleanup

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/lessons#23]
There are a LOT Of really great suggestions in #12 from @willingc and @sneakers-the-rat ! Because the fall festival is quickly approaching, I am going to merge that PR after committing to all of the inline suggestions. 

After that, we need to pull all of the content and feedback from that PR and address it in individual PRs! 
@sneakers-the-rat, feel free to open PRs that address any of your comments. I'll start moving some of them to issues now, but I may not get to all of them before the fall festival. Perhaps we can implement some of them together?

However, we will address them all in the upcoming weeks and months, as they are all great!! Right now, I've created a new team: a lesson dev team. Jeremiah, both of you and i are members. all members have `maintain` level permissions on this repo!!

Thank you so much for all of the great feedback. Its really going to improve these lessons a lot!!

**Comment by willingc** [comment]
Closed by #31
