### ISSUE TITLE
Zenodo / share code lesson activity topics

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/lessons#43]
The activities for these lessons might be best if we focus on:

- [x] forking a repo that has a [package in it](https://github.com/pyOpenSci/pyosPackage). If they want to edit it, they could do so in codespaces (pyospackage repo already has a vscode codespace setup thanks to sarah!)
- [x] if they know git and github they can commit their code to a new repo but otherwise i can just show them how to do this all using the GitHub gui (so the bare minimum requirement is a GitHub account
- [x] Connect the repo with zenodo. (they can login to zenodo with their ORCID or GitHub
- [x] Create a release of the code (GitHub)
- [x] Grab the badge from zenodo (understand all versions vs sub dois representing release versions)
- [x] Add badge to the README file. 
- [x] Optional: create a citation file??

What's missing

- [x] Have them add a CITATION.cff file and possibly to flesh out the readme and link to that citation info. 
- [x] Add a citation.cff file to our pyospackage repo so it's there

**Comment by willingc** [comment]
@lwasser I like this. Do you want to checkoff those that are done?

**Comment by lwasser** [comment]
This pr has been largely addressed in #62 ! I've updated the two missing pieces in the list above! once those are done we can close this issue!
