### ISSUE TITLE
Create a DOI for these lessons

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/lessons#64]
We should create a DOI for the lessons and add to our README either before or after the Fall Festival.

The current README links to the Packaging Guide :smile:

**Comment by lwasser** [comment]
@willingc thank you for this!! Can you please double check this as I think the DOI is resolving correctly now? BUT i could be missing something!! it's very possible that I copied something somewhere incorrectly. i'll test out a release now to see if it includes you and jonny!

**Comment by willingc** [comment]
Beautiful!
